### ISSUE TITLE
draw route?

### ISSUE THREAD

**Issue by kmolLin** [discomethod/pad-helper#1]
Can it  coucrate the more best route and show the answer on anther screen ? 
Can't it to cocurate the route like the video on youtube(underline) ?

https://www.youtube.com/watch?v=iRyNR3vLvK8

**Comment by discomethod** [comment]
Figuring out how to represent the optimal path is quite a tricky problem. The method used in the video is only for illustrative purposes, since it doesn't capture what the path should be when it intersects itself. It doesn't actually uniquely specify the path the player should make.

This is related to a more fundamental problem with using a program to assist in playing Puzzle and Dragons. Following a prescribed path is not the intuitive way most people play Puzzle and Dragons. An ideal solver would help the user visualize the intermediate stages on the way to the final solved board (e.g., make a 4-match of red orbs in the bottom corner, then a 3-match column of green orbs above it, etc.).
